language: rust

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh | bash

env:
  global:
    secure: bO2zEC65wfaZfBiI75dFDyshfoDePgEc0muOO+OkcJwojqDYYPuL8qvEO4hmeTKslPs2Te9PRD+edldu6viVtONfYy22AzlKlnQd/K0+HsM+CZIhYqPq3+IbgKhGeLxrPh0Q05PMCzpK1cBM4OXPFM8+QsY4ulZ2sNEOSAFpxeM=

notifications:
  email:
    on_success: never
