[package]
name = "libtar-sys"
version = "0.1.4"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/libtar-sys"
homepage = "https://github.com/stainless-steel/libtar-sys"
description = "The library facilitates static linking with libtar."
links = "tar"
build = "build.rs"

[dependencies]
libc = "*"
